--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9
-- Dumped by pg_dump version 16.9

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: balance_top_ups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.balance_top_ups (
    id bigint NOT NULL,
    amount double precision NOT NULL,
    "time" timestamp(6) without time zone,
    current_account_id bigint
);


ALTER TABLE public.balance_top_ups OWNER TO postgres;

--
-- Name: balance_top_ups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.balance_top_ups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.balance_top_ups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: current_accounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.current_accounts (
    id bigint NOT NULL,
    balance double precision NOT NULL
);


ALTER TABLE public.current_accounts OWNER TO postgres;

--
-- Name: current_accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.current_accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.current_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: current_accounts_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.current_accounts_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.current_accounts_seq OWNER TO postgres;

--
-- Name: number_plates; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.number_plates (
    id bigint NOT NULL,
    number character varying(7) NOT NULL
);


ALTER TABLE public.number_plates OWNER TO postgres;

--
-- Name: number_plates_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.number_plates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.number_plates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: number_plates_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.number_plates_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.number_plates_seq OWNER TO postgres;

--
-- Name: parking_sessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.parking_sessions (
    id bigint NOT NULL,
    amount double precision,
    end_time timestamp(6) without time zone,
    start_time timestamp(6) without time zone NOT NULL,
    current_account_id bigint,
    number_plate_id bigint
);


ALTER TABLE public.parking_sessions OWNER TO postgres;

--
-- Name: parking_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.parking_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parking_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.user_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.user_seq OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    mail character varying(320) NOT NULL,
    password character varying(255) NOT NULL,
    phone_number character varying(10) NOT NULL,
    current_account_id bigint
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_number_plates; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_number_plates (
    user_id bigint NOT NULL,
    number_plate_id bigint NOT NULL
);


ALTER TABLE public.users_number_plates OWNER TO postgres;

--
-- Name: users_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.users_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_seq OWNER TO postgres;

--
-- Name: balance_top_ups balance_top_ups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.balance_top_ups
    ADD CONSTRAINT balance_top_ups_pkey PRIMARY KEY (id);


--
-- Name: current_accounts current_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.current_accounts
    ADD CONSTRAINT current_accounts_pkey PRIMARY KEY (id);


--
-- Name: number_plates number_plates_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.number_plates
    ADD CONSTRAINT number_plates_pkey PRIMARY KEY (id);


--
-- Name: parking_sessions parking_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parking_sessions
    ADD CONSTRAINT parking_sessions_pkey PRIMARY KEY (id);


--
-- Name: number_plates uk5va79l7y6p6f4wwxx11nldofw; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.number_plates
    ADD CONSTRAINT uk5va79l7y6p6f4wwxx11nldofw UNIQUE (number);


--
-- Name: users uk7egf5a9mb54ssww9hiem53vxu; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk7egf5a9mb54ssww9hiem53vxu UNIQUE (current_account_id);


--
-- Name: users uk9q63snka3mdh91as4io72espi; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk9q63snka3mdh91as4io72espi UNIQUE (phone_number);


--
-- Name: users ukjhck7kjdogc7yia7qamc89ypv; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukjhck7kjdogc7yia7qamc89ypv UNIQUE (mail);


--
-- Name: users_number_plates users_number_plates_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_number_plates
    ADD CONSTRAINT users_number_plates_pkey PRIMARY KEY (user_id, number_plate_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: balance_top_ups fk7m0v8m98h2ubly8uvt4mam10i; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.balance_top_ups
    ADD CONSTRAINT fk7m0v8m98h2ubly8uvt4mam10i FOREIGN KEY (current_account_id) REFERENCES public.current_accounts(id);


--
-- Name: users fk8iygop8dfj8mcfjs4al9vusn0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk8iygop8dfj8mcfjs4al9vusn0 FOREIGN KEY (current_account_id) REFERENCES public.current_accounts(id);


--
-- Name: parking_sessions fkh6xnsw32d69jvj8nkefulhpjn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parking_sessions
    ADD CONSTRAINT fkh6xnsw32d69jvj8nkefulhpjn FOREIGN KEY (current_account_id) REFERENCES public.current_accounts(id);


--
-- Name: users_number_plates fkhlv3h74s9v5r7j1p2c1ml6vkj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_number_plates
    ADD CONSTRAINT fkhlv3h74s9v5r7j1p2c1ml6vkj FOREIGN KEY (number_plate_id) REFERENCES public.number_plates(id);


--
-- Name: parking_sessions fkkltyevq3l7wa3sln2pvgrn1rt; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parking_sessions
    ADD CONSTRAINT fkkltyevq3l7wa3sln2pvgrn1rt FOREIGN KEY (number_plate_id) REFERENCES public.number_plates(id);


--
-- Name: users_number_plates fkmffqaot0791ywg1ds1fk2fdct; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_number_plates
    ADD CONSTRAINT fkmffqaot0791ywg1ds1fk2fdct FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

